---
apiVersion: v1
kind: ConfigMap
metadata:
  name: containership-env-configmap
  namespace: containership-core
  labels:
      containership.io/managed: "true"
data:
  CONTAINERSHIP_CLOUD_ENVIRONMENT: "development"
  CONTAINERSHIP_CLOUD_SYNC_INTERVAL_SEC: "15s"
  AGENT_INFORMER_SYNC_INTERVAL_SEC: "30s"
  COORDINATOR_INFORMER_SYNC_INTERVAL_SEC: "30s"
  CONTAINERSHIP_CLOUD_CLUSTER_API_KEY: ""
  CONTAINERSHIP_CLOUD_ORGANIZATION_ID: ""
  CONTAINERSHIP_CLOUD_CLUSTER_ID: ""
