---
# Note: Only Kubernetes v1.8+ clusters supported
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  namespace: containership-core
  name: containership-agent
  labels:
    app: containership-agent
    tier: cloud-synchronize
    version: v1
spec:
  selector:
    matchLabels:
      app: containership-agent
  template:
    metadata:
      labels:
        app: containership-agent
        name: cloud-agent
    spec:
      volumes:
        - name: code
          hostPath:
              path: /Users/.minikube-mounts/internal
        - name: containership-volume
          hostPath:
              path: /etc/containership
              type: DirectoryOrCreate
        - name: containership-home
          hostPath:
              path: /etc/containership/home
              type: DirectoryOrCreate
        - name: containership-scripts
          hostPath:
              path: /etc/containership/scripts
              type: DirectoryOrCreate
      containers:
        - name: containership-agent
          envFrom:
            - configMapRef:
                name: containership-env-configmap
          env:
            - name: NODE_PRIVATE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          image: agent:debug
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: containership-volume
              mountPath: /etc/containership
            - name: containership-home
              mountPath: /etc/containership/home
            - name: containership-scripts
              mountPath: /etc/containership/scripts
          resources:
            requests:
              cpu: 0.15
          securityContext:
            privileged: true
