---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  namespace: containership-core
  name: containership-agent
  labels:
    app: containership-agent
    version: v1
spec:
  template:
    metadata:
      labels:
        app: containership-agent
        name: containership
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/master" #kubernetes.io/role=master
          effect: "NoSchedule"
      containers:
        - name: containership-agent
          envFrom:
            - configMapRef:
              name: containership-env-configmap
          env:
            - name: NODE_PRIVATE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          image: ashleyschuett/cloud-agent:debug
          command: ["/app/containership", "agent"]
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 0.15
          securityContext:
            privileged: true
