---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: containership-core
  name: containership-coordinator
  labels:
    app: containership-coordinator
    version: v1
spec:
  template:
    metadata:
      labels:
        app: containership-coordinator
        name: cloud-coordinator
    spec:
      containers:
        - name: containership-coordinator
          envFrom:
            - configMapRef:
              name: containership-env-configmap
          env:
            - name: NODE_PRIVATE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          image: ashleyschuett/cloud-agent:debug
          command: ["/app/containership", "coordinator"]
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 0.15
          securityContext:
            privileged: true
