---
# Note / TODO: this is mostly just for testing with GKE now. In production for
# BYOC case we will probably not be able to tell if RBAC is enabled.
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: containership-rbac
  labels:
    containership.io: managed
subjects:
  - kind: ServiceAccount
  # Reference to upper's `metadata.name`
    name: default
    # Reference to upper's `metadata.namespace`
    namespace: containership-core
roleRef:
  kind: ClusterRole
  name: containership-rbac
  apiGroup: rbac.authorization.k8s.io
