apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nodepoollabels.provision.containership.io
  labels:
    containership.io/managed: "true"
spec:
  group: provision.containership.io
  # Version should match Containership Cloud API version
  version: v3
  scope: Namespaced
  names:
    kind: NodePoolLabel
    plural: nodepoollabels
    shortNames:
    - npl
